---
title: Publications
---
## Employment

**2019 – Present** -> **Auxiliary Researcher** at Centro de Investigação em Biodiversidade e Recursos Genéticos ([CIBIO-InBIO](https://cibio.up.pt/))

**2011 – Present** -> **Data analyst and Biodiversity and Ecosystem Services consultant** at [Associação Natureza Portugal/WWF Portugal](http://www.wwf.pt)

**2016 – 2018** ->   **Postdoctoral fellow** at Centro de Ecologia Aplicada “Prof. Baeta Neves”/Instituto Superior de Agronomia ([CEABN](http://www.isa.ulisboa.pt/ceabn/content/1/80/homepage))

**2011 – 2015** ->  **PhD Candidate** at [Centro de Ecologia Aplicada “Prof. Baeta Neves”](http://www.isa.ulisboa.pt/ceabn/) and [Instituto Superior de Agronomia, Universidade de Lisboa](htpp://www.isa.ulisboa.pt)

**2008 – 2009** -> **Research assistant** at the [Faculty of Sciences of the University of Lisbon](http://www.fc.ul.pt)

---

## Education

**2011 – 2015** -> **PhD in Forestry and Natural Resources, Instituto Superior de Agronomia da Universidade de Lisboa**

Advisors: Miguel N. Bugalho and Jorge Orestes Cerdeira

Thesis: The Role of Forest Certification for the Conservation of Biodiversity and Sustainability of Cork Oak Woodlands

**2007 – 2008** ->  **MSc in Conservation Biology, Faculty of Sciences of the University of Lisbon**

Advisor: Margarida Santos-Reis

Thesis: Multi-Scale Analysis of Carnivores’ Road Mortality Patterns in Highways: A Case Study with the Stone Marten and the Common Genet

**2003 - 2007** ->  **Degree in Environmental Biology, Faculty of Sciences of the University of Lisbon**

---

## Student supervisions

Berta Briñas García, Erasmus Mundus MSc in Mediterranean Forestry and Natural Resources Management with Doctor [Miguel N. Bugalho](https://scholar.google.pt/citations?hl=en&user=HoiEreEAAAAJ&view_op=list_works&sortby=pubdate) (CEABN/ISA). Thesis title: "Mapping and identification of hotspots for biodiversity and ecosystem services in cork oak woodlands in Portugal."

