# This file controls the settings for your Quarto template from www.marvinschmitt.com

# website settings
website:
  title: "Filipe S. Dias"                                # Your name
  description: "Gandalf is a renowned wizard and scholar of Middle-earth"   # A brief slogan (optional)
  image: img/my_image.jpg
  
  favicon: img/favicon.png
  
  # start of the navigation bar at the top of the website
  navbar:
    pinned: true
    logo: /img/logo.png
    
    # your sub-pages
    left:
      - text: "Publications"
        href: publications/index_publications.qmd
      - text: "CV"
        href: cv/index_cv.qmd
      - text: "Knowledge base"
        href: knowledge_base/index_kb.qmd
        
    # your social media handles
    right:
      - icon: twitter
        href: https://twitter.com/fsdias8
      
      - icon: envelope
        aria-label: email
        href: "mailto:fsdias@gmx.com"  
  
  

# Don't touch unless you know what you are doing :) ------------
  search: 
    location: navbar
    type: textbox
  page-footer: 
    left: |
      <span class="faux-block">&#169; 2023 Marvin Schmitt CC BY-SA 4.0</span>
   
    right: |
      <span class="faux-block"><a href="https://github.com/marvinschmitt/quarto-website-template/">View original template</a></span>

project:
  type: website
  output-dir: docs

  preview: 
    port: 22222
    browser: true
    watch-inputs: true
    navigate: true

execute:
  freeze: true

format:
  html:
    fontsize: 1.1em
    theme: 
      - pulse
      - html/styles.scss
    toc: false
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true