---
title: Publications
---

## Journal articles

**Dias, Filipe S.**, Michael Betancourt, Patricia María Rodríguez-González, and Luís Borda-de-Água. “BetaBayes—A Bayesian Approach for Comparing Ecological Communities.” Diversity 14, no. 10 (October 2022): 858. [https://www.mdpi.com/1424-2818/14/10/858/htm](https://www.mdpi.com/1424-2818/14/10/858/htm)

Pabst, Rebecca, **Filipe S. Dias**, Luís Borda-de-Água, Patricia María Rodríguez-González, and César Capinha. “Assessing and Predicting the Distribution of Riparian Invasive Plants in Continental Portugal.” Frontiers in Ecology and Evolution 10 (May 6, 2022): 875578. [https://doi.org/10.3389/fevo.2022.875578](https://doi.org/10.3389/fevo.2022.875578)


**Dias, Filipe S.**, Michael Betancourt, Patricia María Rodríguez-González, and Luís Borda-de-Água. “Analysing the Distance Decay of Community Similarity in River Networks Using Bayesian Methods.” Scientific Reports 11, no. 1 (November 4, 2021): 21660. [https://doi.org/10.1038/s41598-021-01149-x](https://doi.org/10.1038/s41598-021-01149-x)

Acácio, Vanda, **Filipe S. Dias**, Filipe X. Catry, Miguel N. Bugalho, and Francisco Moreira. “Canopy Cover Loss of Mediterranean Oak Woodlands: Long-Term Effects of Management and Climate.” Ecosystems, March 16, 2021. [https://doi.org/10.1007/s10021-021-00617-9](https://doi.org/10.1007/s10021-021-00617-9)

Romeiras, Maria M, Mark Carine, Maria Cristina Duarte, Sílvia Catarino, **Filipe S. Dias**, and Luís Borda-de-Água. “Bayesian Methods to Analyze Historical Collections in Time and Space: A Case Study Using Cabo Verde Endemic Flora.” Frontiers in Plant Science 11, no. 278 (2020): 12.[https://doi.org/10.3389/fpls.2020.00278](https://doi.org/10.3389/fpls.2020.00278)

**Dias, Filipe S.**, José F. C. Wenceslau, Tiago A. Marques, and David L. Miller. “Density and Distribution of Western Chimpanzees around a Bauxite Deposit in the Boé Sector, Guinea-Bissau.” American Journal of Primatology 81, no. 9 (2019): e23047. [https://doi.org/10.1002/ajp.23047](https://doi.org/10.1002/ajp.23047)

Arsénio, Pedro, Patricia María Rodríguez-González, Ivan Bernez, **Filipe S. Dias**, Miguel Nunes Bugalho, and Simon Dufour. “Riparian Vegetation Restoration: Does Social Perception Reflect Ecological Value?: Social Perception of Riparian Vegetation Restoration.” River Research and Applications, August 20, 2019. [https://doi.org/10.1002/rra.3514](https://doi.org/10.1002/rra.3514)

Acácio, Vanda, **Filipe S. Dias**, Filipe X. Catry, Marta Rocha, and Francisco Moreira. “Landscape Dynamics in Mediterranean Oak Forests under Global Change: Understanding the Role of Anthropogenic and Environmental Drivers across Forest Types.” Global Change Biology 23, no. 3 (March 1, 2017): 1199–1217. [https://doi.org/10.1111/gcb.13487](https://doi.org/10.1111/gcb.13487)


**Dias, Filipe S.**, David L. Miller, Tiago A. Marques, Joana Marcelino, Maria C. Caldeira, J. Orestes Cerdeira, and Miguel N. Bugalho. “Conservation Zones Promote Oak Regeneration and Shrub Diversity in Certified Mediterranean Oak Woodlands.” Biological Conservation 195 (March 2016): 226–34. [https://doi.org/10.1016/j.biocon.2016.01.009](https://doi.org/10.1016/j.biocon.2016.01.009)


**Dias, Filipe S.**, M N Bugalho, B. Briñas, and J. O. Cerdeira. “Using the High Conservation Value Forest Concept and Pareto Optimization to Identify Areas Maximizing Biodiversity and Ecosystem Services in Cork Oak Landscapes.” Agroforestry Systems, April 19, 2015. [https://doi.org/10.1007/s10457-015-9814-x](https://doi.org/10.1007/s10457-015-9814-x)

**Dias, Filipe S.**, Miguel N. Bugalho, Patricia M. Rodríguez-González, António Albuquerque, and J. Orestes Cerdeira. “Effects of Forest Certification on the Ecological Condition of Mediterranean Streams.” Edited by Angela Strecker. Journal of Applied Ecology 52, no. 1 (February 2015): 190–98. [https://doi.org/10.1111/1365-2664.12358](https://doi.org/10.1111/1365-2664.12358)


**Dias, Filipe S.**, Miguel N. Bugalho, J. Orestes Cerdeira, and M. João Martins. “Is Forest Certification Targeting Areas of High Biodiversity in Cork Oak Savannas?” Biodiversity and Conservation 22 (November 2013): 93–112. [https://doi.org/10.1007/s10531-012-0401-4](https://doi.org/10.1007/s10531-012-0401-4)

---

## Thesis

**Dias, Filipe S.**. “The Role of Forest Certification for the Conservation of Biodiversity and Sustainability of Cork Oak Woodlands.” Instituto Superior de Agronomia, Universidade de Lisboa, 2015. PhD Thesis [Link](https://www.repository.utl.pt/handle/10400.5/12021?locale=en)

**Dias, Filipe S**. “Multi-Scale Analysis of Carnivores’ Road Mortality Patterns in Highways: A Case Study with the Stone Marten and the Common Genet.” Faculdade de Ciências da Universidade de Lisboa, 2008. MsC Thesis

---

## Selected talks

**Dias, Filipe S.**, Michael Betancourt, Patricia María Rodríguez-González, and Luís Borda-de-Água. “Analysing the distance decay of community similarity in river networks using Bayesian methods.” 20º Encontro Nacional de Ecologia, December 1-4, Escola Superior Agrária Ponte de Lima. [Slides](https://fsdias.github.io/presentations/speco21/)

**Dias, Filipe S.**, "How to Manage and Process Big Datasets in R - an Example with eBird Data", Journal Club, March 23th [Slides](https://fsdias.github.io/presentations/bigdata/)

--- 

## Reports

Bugalho, Miguel N., **Filipe S. Dias**, and Rui Barreira. “Incêndios Rurais Em Portugal: Até Quando Deixaremos a Paisagem Arder?” Lisboa, Portugal: WWF Mediterrâneo (WWF MED)/Centro de Ecologia Aplicada Prof. Baeta Neves do Instituto Superior de Agronomia (CEABN/ISA), 2017. [Link](https://wwfeu.awsassets.panda.org/downloads/incendios_relatorio_vfinal_1.pdf)


Branco, Orlando, Miguel Nuno Bugalho, Luís Neves Silva, Rui Barreira, Pedro Vaz, and **Filipe S. Dias**. “Hotspot Areas for Biodiversity and Ecosystem Services in Montado.” Lisbon: WWF Mediterranean – Portugal/Centre for Applied Ecology Prof. Baeta Neves(CEABN), 2010. [Link](http://awsassets.panda.org/downloads/habeas_report2010.pdf)

